'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/src/context/auth-context';
import { Baby, Sparkles, Heart, Gift } from 'lucide-react';
import { Button } from '@/components/ui/button';
import Link from 'next/link';

export default function LandingPage() {
  const { user, loading } = useAuth();
  const router = useRouter();
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  useEffect(() => {
    if (mounted && !loading) {
      if (user) {
        router.push('/dashboard');
      }
    }
  }, [user, loading, router, mounted]);

  // Show loading state while checking auth
  if (!mounted || loading) {
    return (
      <div className="flex justify-center items-center min-h-screen bg-accent">
        <div className="text-center">
          <Baby className="h-16 w-16 mx-auto mb-4 text-primary animate-pulse" />
          <h1 className="text-4xl font-headline text-primary">Passy</h1>
          <p className="text-muted-foreground mt-2">Loading...</p>
        </div>
      </div>
    );
  }

  // Show landing page if not authenticated
  return (
    <div className="min-h-screen bg-gradient-to-b from-accent to-background">
      <div className="container mx-auto px-4 py-16">
        <div className="text-center max-w-4xl mx-auto">
          {/* Hero Section */}
          <div className="mb-12">
            <Baby className="h-20 w-20 mx-auto mb-6 text-primary" />
            <h1 className="text-6xl font-headline text-primary mb-4">Passy</h1>
            <p className="text-2xl text-muted-foreground mb-2">Baby Shower Planner</p>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              The simplest way to plan a beautiful, memorable baby shower with AI-powered assistance
            </p>
          </div>

          {/* Features Grid */}
          <div className="grid md:grid-cols-3 gap-6 mb-12">
            <div className="p-6 rounded-lg bg-card border shadow-sm">
              <Sparkles className="h-10 w-10 mx-auto mb-4 text-primary" />
              <h3 className="font-headline text-xl mb-2">AI Theme Assistant</h3>
              <p className="text-sm text-muted-foreground">
                Get creative theme ideas with visual images generated by AI
              </p>
            </div>
            
            <div className="p-6 rounded-lg bg-card border shadow-sm">
              <Heart className="h-10 w-10 mx-auto mb-4 text-primary" />
              <h3 className="font-headline text-xl mb-2">Smart Planning</h3>
              <p className="text-sm text-muted-foreground">
                Manage guests, budget, checklist, and registry all in one place
              </p>
            </div>
            
            <div className="p-6 rounded-lg bg-card border shadow-sm">
              <Gift className="h-10 w-10 mx-auto mb-4 text-primary" />
              <h3 className="font-headline text-xl mb-2">AI Game Ideas</h3>
              <p className="text-sm text-muted-foreground">
                Get personalized game suggestions and thank you note templates
              </p>
            </div>
          </div>

          {/* CTA Buttons */}
          <div className="flex gap-4 justify-center">
            <Link href="/account">
              <Button size="lg" className="font-semibold">
                Get Started Free
              </Button>
            </Link>
            <Link href="/dashboard">
              <Button size="lg" variant="outline" className="font-semibold">
                View Dashboard
              </Button>
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
